---
matrix:
  DRONE_S3_CACHE_BUCKET_NAME:
    - dps-drone-cache

pipeline:
  drone_s3_cache_pull:
    image: quay.io/ukhomeofficedigital/drone-s3cache:v0.2.0
    drone_s3_cache_mode: "pull"
    secrets:
      - DRONE_S3_CACHE_AWS_ACCESS_KEY_ID
      - DRONE_S3_CACHE_AWS_SECRET_ACCESS_KEY
    when:
      event: push

  build:
    commands:
      - /root/entrypoint.sh
      - sbt clean test
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
    environment:
      - ARTIFACTORY_USERNAME=regt-build-bot
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event: push

  drone_s3_cache_push:
    image: quay.io/ukhomeofficedigital/drone-s3cache:v0.2.0
    drone_s3_cache_folders: .ivy2
    drone_s3_cache_mode: "push"
    secrets:
      - DRONE_S3_CACHE_AWS_ACCESS_KEY_ID
      - DRONE_S3_CACHE_AWS_SECRET_ACCESS_KEY
    when:
      event: push

  publish:
    commands:
      - /root/entrypoint.sh
      - sbt '+ publish'
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
    environment:
      - ARTIFACTORY_SERVER=https://artifactory.digital.homeoffice.gov.uk/
      - ARTIFACTORY_USERNAME=regt-build-bot
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event: push
      branch: master

  publish_tag:
    commands:
      - /root/entrypoint.sh
      - sbt "set version := \"$${DRONE_TAG}\"" '+ publish'
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.3.1
    environment:
      - ARTIFACTORY_SERVER=https://artifactory.digital.homeoffice.gov.uk/
      - ARTIFACTORY_USERNAME=regt-build-bot
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event: tag
