---
kind: pipeline
type: kubernetes
name: rtp-mongo-lib

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt:latest
  commands:
  - . /app/entrypoint.sh
  - git fetch --tags
  - sbt clean coverageEnabled test coverageReport coverageOff
  - sbt scalastyle
  - sbt scapegoat || /bin/true
  - sbt +test
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: regt-build-bot
    DB_TEST_HOST: database
    JRE_VERSION: 21
    OVERRIDE_BUILD_REPOS: "false"
    HOME: "/app"
  when:
    event:
    - push
    - tag

- name: dependency_check
  pull: Always
  image: owasp/dependency-check:latest
  commands:
    - "/usr/share/dependency-check/bin/dependency-check.sh --scan . || /bin/true"
  when:
    event:
    - push
  depends_on:
    - build

- name: sonar-scanner
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner:v4.6
  commands:
  - sonar-scanner
  when:
    event:
    - push
    - tag
  depends_on:
    - dependency_check

- name: publish
  pull: Always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/rtge/scala-sbt:latest
  commands:
  - . /app/entrypoint.sh
  - sbt +publish
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_SERVER: https://artifactory.digital.homeoffice.gov.uk/
    ARTIFACTORY_USERNAME: regt-build-bot
    JRE_VERSION: 21
    OVERRIDE_BUILD_REPOS: "false"
  when:
    branch:
    - master
    event:
    - push
    - tag
  depends_on:
    - sonar-scanner

services:
  - name: database
    pull: if-not-exists
    image: mongo:5.0
